### ISSUE TITLE
Update to 0.2.2?

### ISSUE THREAD

**Issue by SergeyDjam** [TokTok/go-toxcore-c#11]
Hi. What plans for up-dating for a 0.2.2 version  toxcore?

**Comment by envsh** [comment]
The master is already compatiable with 0.2.2

**Comment by SergeyDjam** [comment]
Hm, this no build

**Comment by nurupo** [comment]
Sounds like you are missing toxav library.

**Comment by SergeyDjam** [comment]
rpm -qa | grep tox
pidgin-plugin-tox-0.5.1-2-rosa2014.1.x86_64
c-toxcore-0.2.2-1-rosa2014.1.x86_64
c-toxcore-devel-0.2.2-1-rosa2014.1.x86_64
lib64toxcore2-0.2.2-1-rosa2014.1.x86_64
lib64toxav2-0.2.2-1-rosa2014.1.x86_64
lib64toxencryptsave2-0.2.2-1-rosa2014.1.x86_64
lib64toxcore-devel-0.2.2-1-rosa2014.1.x86_64
lib64toxencryptsave-devel-0.2.2-1-rosa2014.1.x86_64
lib64toxav-devel-0.2.2-1-rosa2014.1.x86_64
qtox-1.15.0-1-rosa2014.1.x86_64

ld -ltoxav
ld: warning: cannot find entry symbol _start; not setting start address

????

**Comment by nxshock** [comment]
@SergeyDjam 
Make sure you have `toxav.h`, `toxencryptsave.h`, `tox.h` in `/usr/include/tox`.

**Comment by iphydf** [comment]
Is this still an issue? We run travis tests against 0.2.3 (actually master).

**Comment by SergeyDjam** [comment]
Thanks. Its works
