### ISSUE TITLE
cant build do to error

### ISSUE THREAD

**Issue by blackpungas** [TokTok/go-toxcore-c#52]
hi there, i tried hard to solve this by myself but failed, i trully dont know what is this:

../../go/pkg/mod/github.com/!tok!tok/go-toxcore-c@v0.2.17/toxav.go:319:48: could not determine kind of name for C.toxav_audio_data_cb

does anybody now how to solve that?

**Comment by blackpungas** [comment]
oh, I found what i needed it

**Comment by tarumes** [comment]
and what?
because i have the same error

**Comment by liadala** [comment]
me too what do i have to do to fix this?
